[audio]
enable_overdrive = true

[bar.default]
background_opacity = 1.0
border = "on_error"
capsule_padding = 10.0
capsule_thickness = 0.99999998137354851
center = []
concave_edge_corners = false
end = [ "tray", "network", "battery", "volume", "bluetooth", "brightness", "notifications", "clock", "control-center" ]
font_family = "JetBrainsMono NFP"
margin_ends = 0
panel_overlap = 0
position = "bottom"
radius = 0
shadow = false
start = [ "launcher", "workspaces", "taskbar" ]
thickness = 30
widget_spacing = 15

[brightness]
enable_ddcutil = true

[calendar]

[control_center]
sidebar = "full"
sidebar_section = "full"

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
background_opacity = 0.59999998658895493
cross_axis_padding = 5
enabled = false
icon_size = 32
item_spacing = 5
launcher_position = "start"
magnification_scale = 1.2000000029802322
main_axis_padding = 5
pinned = [ "firefox", "org.kde.dolphin" ]
radius = 5
reserve_space = false
shadow = false
show_dots = true

[location]
auto_locate = true
sunrise = "06:00"
sunset = "18:00"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1", "lockscreen-login-box@HEADLESS-1" ]

[nightlight]
enabled = true
force = false
temperature_night = 4400

[osd.kinds]
keyboard_layout = false
media = false
power_profile = false

[shell]
font_family = "JetBrainsMono NFP"
telemetry_enabled = false

    [shell.panel]
    open_near_click_control_center = true
    open_near_click_launcher = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "kcolorscheme", "qt" ]
    enable_builtin_templates = true
    enable_community_templates = false

        [theme.templates.user.labwc-themerc]
        input_path = "~/.config/noctalia/templates/labwc.conf"
        output_path = "~/.config/labwc/themerc-override"
        post_hook = "labwc --reconfigure"

        [theme.templates.user.niri-themerc]
        input_path = "~/.config/noctalia/templates/niri.conf"
        output_path = "~/.config/niri/noctalia-layout.kdl"
        post_hook = "niri msg action load-config-file"

        [theme.templates.user.zathura]
        input_path_modes = { dark = "~/.config/noctalia/templates/zathura-dark.theme", light = "~/.config/noctalia/templates/zathura-light.theme" }
        output_path = "~/.config/zathura/themes/noctalia.theme"

[wallpaper]
directory = "/home/mikejohnp/bg"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.brightness]
show_label = false

[widget.network]
show_label = false

[widget.taskbar]
icon_scale = 1.2000000000000002
inactive_opacity = 0.7
item_spacing = 8
only_active_workspace = true
show_all_outputs = false
show_window_title = true

[widget.volume]
show_label = false

[widget.workspaces]
show_labels = true
style = "minimal"

