layout {
    focus-ring {
        // Uncomment this line to disable the focus ring.
        off

        active-color "{{colors.primary.default.hex}}"

        inactive-color "#00000000"

        // active-gradient from="{{colors.primary.default.hex}}" to="{{colors.secondary.default.hex}}" angle=45

        // inactive-gradient from="{{colors.outline.default.hex}}" to="{{colors.outline.default.hex}}" angle=45 relative-to="workspace-view"
    }

    border {
        // The settings are the same as for the focus ring.
        // If you enable the border, you probably want to disable the focus ring.
        // off

        width 1.5

        active-color "{{colors.primary.default.hex}}"

        inactive-color "#00000000"

        urgent-color   "{{colors.error.default.hex}}"

        // active-gradient from="{{colors.primary.default.hex}}" to="{{colors.secondary.default.hex}}" angle=45 relative-to="workspace-view"

        // inactive-gradient from="{{colors.outline.default.hex}}" to="{{colors.outline.default.hex}}" angle=45 relative-to="workspace-view"
    }

}
