# ==========================================
# Status Bar Configuration (Standard UTF-8 / Minimal)
# ==========================================
set -g status-position bottom
set -g status-style "bg=default"
set -g status-justify "left"

# Style
set -g @blk_text "#[fg=#{@tk_fg},bg=#{@tk_bg},nobold]"
set -g @blk_gap "#[fg=default,bg=default,none]"

# status left look and feel
set -g status-left-length 80
set -g status-left ""

# status left modules
set -ga status-left "#[fg=#{@tk_black},bg=#{@tk_green},bold]#{?client_prefix,#[bg=#{@tk_red}],} ❯ #S #{E:#{@blk_gap}}"

# status right look and feel
set -g status-right-length 200
set -g status-right ""

# how often the status bar is redrawn, keeps the cpu/ram values moving
set -g status-interval 5

# system metrics and weather, skipped on hosts without the dot-tmux-stat script
if-shell 'command -v dot-tmux-stat' {
    # set -ga status-right "#[fg=#{@tk_yellow},bg=#{@tk_bg},bold]☀ #{E:#{@blk_text}}#(dot-tmux-stat weather) #{E:#{@blk_gap}}"
    set -ga status-right "#[fg=#{@tk_yellow},bg=#{@tk_bg},bold]⚙ #{E:#{@blk_text}}#(dot-tmux-stat cpu) #(dot-tmux-stat temp) #{E:#{@blk_gap}}"
}

# status right modules
set -ga status-right "#[fg=#{@tk_magenta},bg=#{@tk_bg},bold]⌂ #{E:#{@blk_text}}#{b:pane_current_path} #{E:#{@blk_gap}}"
set -ga status-right "#[fg=#{@tk_magenta},bg=#{@tk_bg},bold]◷ #{E:#{@blk_text}}%H:%M #{E:#{@blk_gap}}"

default_window_terminal=""
default_window_number="#[fg=#{@tk_white},bg=#{@tk_surface_0},none] #I "
default_window_name="#[fg=#{@tk_subtext},bg=#{@tk_bg},nobold] #{?#{==:#{window_name},window},#{pane_current_command},#W} "
default_window_panes=""
default_window_flags="\
#{?#{window_marked_flag},* ,}\
#{?#{window_zoomed_flag},[Z] ,}\
#[default]"

current_window_terminal=""
current_window_number="#[fg=#{@tk_black},bg=#{@tk_magenta},bold] #I "
current_window_name="#[fg=#{@tk_magenta},bg=#{@tk_bg},bold] #{?#{==:#{window_name},window},#{pane_current_command},#W} "
current_window_panes=""
current_window_flags="#[fg=#{@tk_yellow}]\
#{?#{window_marked_flag},* ,}\
#{?#{window_zoomed_flag},[Z] ,}\
#[default]"

# --- WINDOW STATUS FORMAT ---
set -g window-status-separator ""
set -g window-status-format "$default_window_terminal$default_window_name$default_window_flags$default_window_panes$default_window_number"
set -g window-status-style "bg=default"

set -g window-status-current-format "$current_window_terminal$current_window_name$current_window_flags$current_window_panes$current_window_number"
set -g window-status-current-style "bg=default"
